general.import = [
    "~/.config/alacritty/themes/themes/one_dark_mine.toml"
]

[font]
normal = { family = "monospace", style = "Regular"}
size = 14

[window]
padding = {x = 8, y = 4}
opacity = 0.9

[terminal.shell]
program = "/usr/bin/fish"
